---
title: "glycodash_spectra_curation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{glycodash_spectra_curation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}

#library(glycodash)
devtools::load_all()

data("long_data")
```

```{r check_criteria}

# Now I'm using the negative controls that were uncalibrated (or for other reason NA)
# as 0 in the calculation of cut-offs (because I replace NAs in the criteria check 
# with FALSE). Is that what we want?

long_data <- curate_spectra(data = long_data,
                            min_ppm_deviation = -20,
                            max_ppm_deviation = 20,
                            max_ipq = 0.2,
                            min_sn = 9,
                            clusters_regex = "IgGI",
                            group_to_filter = "Spike",
                            sample_type_to_filter = "CN")

curated_spectra <- long_data %>% 
  dplyr::filter(passed_spectra_curation == TRUE) %>% 
  dplyr::select(-passed_spectra_curation)

```

```{r visualization}

long_data %>%  
  ggplot2::ggplot() +
  ggplot2::geom_bar(ggplot2::aes(x = sample_type, 
                                 fill = passed_spectra_curation), 
                    position = "fill") +
  ggplot2::facet_wrap(cluster ~ group) +
  ggplot2::xlab("Sample type") +
  ggplot2::scale_y_continuous(labels = function(x) paste0(x * 100, "%"), 
                              name = "Proportion of spectra (%)") +
  ggplot2::scale_fill_discrete(name = "Passed curation?", 
                               labels = c(`TRUE`= "Yes",
                                          `FALSE` = "No"),
                               type = c(`TRUE` = "#3498DB",
                                        `FALSE` = "#E74C3C")) +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
                 strip.background = ggplot2::element_rect(fill = "#F6F6F8")) +
  ggpubr::border(size = 0.5)

# long_data %>% 
#   dplyr::group_by(sample_type, group, passed_curation) %>% 
#   dplyr::summarise(n = length(unique(sample_name)))

```

```{r analyte-curation-based-on-data}

ignore_samples  <- c("Total", "pool", "Visucon")

group_to_ignore <- stringr::str_extract(string = ignore_samples,
                                                 pattern = paste0(unique(curated_spectra$group),
                                                                  collapse = "|")) %>% 
  na.omit(.)
group_to_ignore <- group_to_ignore[!is.na(group_to_ignore)]

sample_types_to_ignore <- stringr::str_extract(string = ignore_samples,
                                               pattern = paste0(unique(curated_spectra$sample_type),
                                                                collapse = "|")) %>% 
  na.omit(.)

sample_types_to_ignore <- sample_types_to_ignore[!is.na(sample_types_to_ignore)]

na.omit(sample_types_to_ignore)

any(!(sample_types_to_ignore %in% curated_spectra$sample_type))


# Analyte curation:
curated_analytes <- curate_analytes(data = curated_spectra,
                                    group_to_ignore = "Total",
                                    sample_types_to_ignore = c("pool", "IVIGg", "CN", "Visucon", "PBS"),
                                    cut_off_percentage = 25)

n_analyte_charge_per_cluster <- curated_spectra %>% 
  dplyr::distinct(., analyte, charge, cluster) %>% 
  dplyr::summarise(n = nrow(.)) %>% 
  as.numeric()

passing_analytes <- curated_analytes %>% 
  dplyr::filter(passed_curation == TRUE) %>% 
  dplyr::select(-passed_curation)

analyte_curated_data <- dplyr::left_join(passing_analytes, curated_spectra)
  
```

```{r plot-analyte-curation}

plot_analyte_curation(curated_analytes = curated_analytes,
                      cut_off_percentage = 25,
                      selected_cluster = "IgGI1H3")
cluster <- "IgGI1H3"
data_to_plot <- curated_analytes %>% 
    dplyr::filter(cluster == cluster)

```

```{r list-with-included-analytes}

create_analyte_curation_table(analyte_curated_data = analyte_curated_data)
                  
```


```{r analyte-curation-based-on-list}

analyte_list_file <- system.file("inst",
                                 "extdata",
                                 "Analyte_list.xlsx",
                                 package = "glycodash")

analyte_list <- readxl::read_excel(analyte_list_file,
                                   col_names = FALSE)
analyte_list <- analyte_list$...1

analytes_to_include <- purrr::map(analyte_list,
                                  function(analyte) {
                                    stringr::str_subset(string = unique(curated_spectra$analyte),
                                                        pattern = paste0(analyte, 
                                                                         "$"))
                                  }) %>% 
  unlist(.)

analyte_curated_data <- curated_spectra %>% 
  dplyr::filter(analyte %in% analytes_to_include)

```

```{r total-absolute-intensity}

total_intensities <- long_data %>% 
    dplyr::mutate(intensity_times_fraction = absolute_intensity_background_subtracted * fraction) %>% 
    dplyr::group_by(sample_name, 
                    analyte) %>% 
    dplyr::summarize(total_absolute_intensity = sum(intensity_times_fraction))

data <- dplyr::full_join(long_data, 
                           total_intensities) 

final_data <- calculate_total_intensity(data = analyte_curated_data)

```

```{r total-area-normalization}

normalize_data <- function(data) {
  
  normalized_data <- final_data %>% 
  dplyr::group_by(cluster, 
                  sample_name) %>% 
  dplyr::summarise(sum_intensity = sum(total_absolute_intensity),
                   across()) %>% 
  dplyr::mutate(relative_abundance = total_absolute_intensity / sum_intensity,
                .keep = "unused")
  
}

normalized_data <- normalize_data(data = final_data) %>% 
  dplyr::ungroup(.)

normalized_data_wide <- normalized_data %>% 
  tidyr::pivot_wider(names_from = c(cluster, analyte),
                     names_sep = "_",
                     values_from = relative_abundance)
  
```

```{r derived-traits-calculation}

row_sum_across <- function(x) {
  rowSums(dplyr::across(dplyr::all_of(x)))
}

calculate_derived_traits <- function(data, derived_traits) {
  analytes <- stringr::str_subset(string = colnames(normalized_data_wide),
                                  pattern = "H\\dN\\d")
  
  data <- data %>%
    dplyr::mutate(sum_all_analytes = row_sum_across(analytes))
  
  if("fucosylation" %in% derived_traits) {
    data <- data %>%
      calculate_fucosylation(., analytes)
  }
  
  if("sialylation" %in% derived_traits) {
    data <- data %>%
      calculate_sialylation(., analytes)
  }
  
  if("galactosylation" %in% derived_traits) {
    data <- data %>%
      calculate_galactosylation(., analytes)
  }
  
  if("bisection" %in% derived_traits) {
    data <- data %>%
      calculate_bisection(., analytes)
  }
  
  return(data)
}

calculate_fucosylation <- function(.data, analytes) {
  
  fucosylated_analytes <- stringr::str_subset(string = analytes,
                                              pattern = "F\\d")
  .data %>% 
    dplyr::mutate(fucosylation = row_sum_across(fucosylated_analytes) / sum_all_analytes)
  
}

calculate_sialylation <- function(.data, analytes) {
  
  monosialylated_analytes <- stringr::str_subset(string = analytes,
                                                 pattern = "S1")
  disialylated_analytes <- stringr::str_subset(string = analytes,
                                               pattern = "S2")
  
  .data %>% 
    dplyr::mutate(monosialylation = row_sum_across(monosialylated_analytes),
                  disialylation = row_sum_across(disialylated_analytes),
                  sialylation = (monosialylation * 1/2 + disialylation) / sum_all_analytes) %>% 
    dplyr::select(-c(monosialylation, disialylation))
  
}

calculate_galactosylation <- function(.data, analytes) {
  
  monogalactosylated_analytes <- stringr::str_subset(string = analytes,
                                                     pattern = "H4")
  digalactosylated_analytes <- stringr::str_subset(string = analytes,
                                                   pattern = "H5")
  
  .data %>% 
    dplyr::mutate(monogalactosylation = row_sum_across(monogalactosylated_analytes),
                  digalactosylation = row_sum_across(digalactosylated_analytes),
                  galactosylation = (monogalactosylation * 1/2 + digalactosylation) / sum_all_analytes) %>% 
    dplyr::select(-c(monogalactosylation, digalactosylation))
}

calculate_bisection <- function(.data, analytes) {
  
  bisected_analytes <- stringr::str_subset(string = analytes,
                                              pattern = "N5")
  .data %>% 
    dplyr::mutate(bisection = row_sum_across(bisected_analytes) / sum_all_analytes)
  
}

normalized_data_wide <- calculate_derived_traits(normalized_data_wide, 
                                                 derived_traits = c("fucosylation",
                                                                    "bisection",
                                                                    "galactosylation",
                                                                    "sialylation"))

```

```{r repeatability-plot}

standard_sample_types <- c("pool")

group_to_plot <- "Spike"

standards <- normalized_data %>% 
  dplyr::filter(sample_type %in% standard_sample_types & group == group_to_plot) %>% 
  dplyr::mutate(plate = stringr::str_extract(plate_well, "^[A-Z]|\\d+")) %>% 
  dplyr::group_by(plate, analyte) %>% 
  dplyr::summarise(average_abundance = mean(relative_abundance * 100),
                   RSD = sd(relative_abundance * 100) / average_abundance * 100 * 5)

ggplot2::ggplot(standards) +
  ggplot2::geom_col(ggplot2::aes(x = analyte, y = average_abundance, fill = plate),
                    position = "dodge") +
  ggplot2::theme_classic() +
  ggpubr::border(size = 0.5) +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45,
                                                     hjust = 1)) +
  ggplot2::geom_point(ggplot2::aes(x = analyte, y = RSD, groups = plate), 
                      position = ggplot2::position_dodge(width = .9)) +
  ggplot2::scale_y_continuous(name = "Relative abundance (%)",
                              labels = function(x) paste0(x, "%"),
                              sec.axis = ggplot2::sec_axis(~ . / 5, 
                                                           name = "RSD (%)",
                                                           labels = function(x) paste0(x, "%"))) +
  ggplot2::scale_x_discrete(name = "Analyte") +
  ggplot2::scale_fill_discrete(name = "Plate")

```

```{r repeatability-table}

```

